## Genetic Algorithm
* Selection
* Crossover
* Mutation

In [2]:
import numpy as np
import random

In [215]:
def fitness_fn(route, dist_mat):
    # calucates fitness function as total distance covered
    
    score = 0
    for i in range(1, len(route)):
        x = route[i-1]
        y = route[i]
        score += dist_mat[x][y]    
    
    return score

In [ ]:
def selection(scores):
    return 2

In [ ]:
def crossover(m,n):
    return n


In [ ]:
def mutate(route, prob, dist_mat):
    return route

In [52]:
def create_random_citymap(prob_sparse,size):
# Create random city map
#    represented using adjacency matrix, symmetrc

    dist_max = 10
    dist_mat = np.zeros((size,size))
    
    for i in range(0,size):
        for j in range (0,i):
            if random.random() > prob_sparse:
                dist_mat[i][j] = int(random.random()*dist_max)
                dist_mat[j][i] = dist_mat[i][j]
    return dist_mat


# np.random.randint(5, size=(2, 4))
# array([[4, 0, 2, 1],
#       [3, 2, 2, 0]])


In [180]:
def rand_soln(dist_mat):
    #
    start = 0
    end = len(dist_mat) - 1
    
    route = np.array([start], dtype=int) # np.zeros(1, dtype=int)
    
    b_val = True
    pos = 0
    
    while b_val:
        values  = np.nonzero(dist_mat[route[pos]])
        rand_val = random.randint(0,len(values[0])-1)
        route = np.append(route, values[0][rand_val])
        
        if route[pos+1] == end :
            b_val = False
        else:
            pos += 1
    
    return route

In [225]:
def generate_population(size, dist_mat):
    # Generate random population of given size
    population = []
    for i in range(0,size):
        population.append(rand_soln(dist_mat))
    return population    

In [231]:
def pop_score_list(pop,dist_mat):
    # returns population fitness score list
    score_list = []
    for route in pop:
        score_list += [fitness_fn(route,dist_mat)]
        
    return score_list    

In [217]:
dm = create_random_citymap(0.01,5)
dm

array([[0., 0., 3., 2., 4.],
       [0., 0., 1., 1., 0.],
       [3., 1., 0., 6., 1.],
       [2., 1., 6., 0., 3.],
       [4., 0., 1., 3., 0.]])

In [218]:
np.nonzero(dm[1])

(array([2, 3]),)

In [219]:
s = rand_soln(dm)
s

array([0, 3, 1, 3, 1, 2, 0, 3, 1, 3, 2, 4])

In [220]:
fitness_fn(s,dm)

20.0

In [228]:
pop = generate_population(3,dm)
pop

[array([0, 2, 0, 4]), array([0, 2, 0, 2, 0, 4]), array([0, 4])]

In [232]:
pop_score_list(pop,dm)

[10.0, 16.0, 4.0]