## Genetic Algorithm
* Selection
* Crossover
* Mutation

In [2]:
import numpy as np
import random

In [3]:
def fitness_fn(route, dist_mat):
    # calucates fitness function as total distance covered
    
    score = 0
    for i in range(1, len(route)):
        x = route[i-1]
        y = route[i]
        score += dist_mat[x][y]    
    score += dist_mat[route[-1]][route[0]]  # back to start
    return score

In [4]:
def selection(pop_scores):
    sort_args = pop_scores.argsort()
    
    return sort_args


In [54]:
def crossover(parent_1,parent_2):
    # ordered crossover
    r1 = int(random.random() * len(parent_1))
    r2 = int(random.random() * len(parent_1))
    start = min(r1,r2)
    end = max(r1,r2)
    
    child = list(parent_1[start:end])
    temp = [item for item in parent_2 if item not in child]
    
    return np.array(child+temp)


In [60]:
def mutate(route):
    # simple mutation without mutation rate , swap any two values
    r1 = int(random.random() * len(route))
    r2 = int(random.random() * len(route))
    route[r1],route[r2] = route[r2],route[r1]
    return route

In [66]:
def create_random_citymap(size):
# Create random city map
#    represented using adjacency matrix, symmetrc
# fully connected

    dist_max = 10
    dist_mat = np.zeros((size,size))
    
    for i in range(0,size):
        for j in range (0,i):
            #if random.random() > prob_sparse:
                dist_mat[i][j] = int(random.random()*dist_max)+1
                dist_mat[j][i] = dist_mat[i][j]
    return dist_mat


# np.random.randint(5, size=(2, 4))
# array([[4, 0, 2, 1],
#       [3, 2, 2, 0]])


In [9]:
def rand_soln_tsp(size):  # contains all nodes
    r_soln = np.arange(size)
    np.random.shuffle(r_soln)
    return r_soln

In [73]:
def generate_population(size, city_count):
    # Generate random population of given size
    population = []
    for i in range(0,size):
        population.append(rand_soln_tsp(city_count))
    return population    

In [124]:
def pick_mate(pop_size):
    return int(random.random() * (pop_size-1))

In [11]:
def pop_score_list(pop,dist_mat):
    # returns population fitness score list
    score_list = []
    for route in pop:
        score_list += [fitness_fn(route,dist_mat)]
        
    return np.array(score_list)    

In [134]:
## utils
def print_verb(iter_c,score_l,pop):
    print("..........")
    print("Iteration :",iter_c)
    print(score_l)
    print(pop)
    print("BEST : ",min(score_l))

In [158]:
def run_genetic_algo(iterations = 5):
    city_count = 6
    population_size = 3
    eliteSize = 1 # Elitism
    offspring_count = 2
    
    distance_mat = create_random_citymap(city_count)
    print(".....DIST MAT.....")
    print(distance_mat)
    print("..........")
    initial_pop = generate_population(population_size,city_count)
    
    best_shortest_d = 999999
    current_pop = initial_pop
    
    for i in range(0,iterations):
       
        
        score_list = pop_score_list(current_pop,distance_mat)
         
        print_verb(i,score_list,current_pop)
        
        best_score = min(score_list)
        best_soln = current_pop[np.argmin(score_list)]
        
        new_pop =[]
        #elitism
        new_pop = [current_pop[pos] for pos in np.argsort(score_list)[:eliteSize]]
        
        # add offspring to population
        for i in range(0,offspring_count):
            off_sp = crossover(current_pop[pick_mate(population_size)],current_pop[pick_mate(population_size)])
            off_sp_m = mutate(off_sp)
            new_pop.append(off_sp_m)
            
       # add random solns
        while len(new_pop) < population_size:
            new_pop.append(rand_soln_tsp(city_count))
        
        # replace old with new copy
        current_pop = new_pop[:]
    
    print('#.#.........FINAL.........#.#')
    print("Best score:",best_score)
    print("Soln :",best_soln)
    print('#.#.........##.........#.#')
    

In [157]:
run_genetic_algo()

.....DIST MAT.....
[[ 0.  3. 10.  9.  6.  4.]
 [ 3.  0.  2.  7.  4.  8.]
 [10.  2.  0. 10.  1.  2.]
 [ 9.  7. 10.  0.  5.  9.]
 [ 6.  4.  1.  5.  0.  5.]
 [ 4.  8.  2.  9.  5.  0.]]
..........
..........
Iteration : 0
[35. 35. 40.]
[array([4, 2, 0, 5, 1, 3]), array([5, 1, 2, 4, 0, 3]), array([1, 3, 2, 0, 5, 4])]
BEST :  35.0
..........
Iteration : 1
[35. 40. 34.]
[array([4, 2, 0, 5, 1, 3]), array([5, 1, 2, 0, 4, 3]), array([4, 0, 1, 5, 2, 3])]
BEST :  34.0
..........
Iteration : 2
[34. 38. 47.]
[array([4, 0, 1, 5, 2, 3]), array([5, 2, 0, 4, 1, 3]), array([5, 1, 4, 0, 2, 3])]
BEST :  34.0
..........
Iteration : 3
[34. 33. 38.]
[array([4, 0, 1, 5, 2, 3]), array([1, 5, 2, 4, 0, 3]), array([5, 2, 0, 4, 1, 3])]
BEST :  33.0
..........
Iteration : 4
[33. 33. 36.]
[array([1, 5, 2, 4, 0, 3]), array([4, 1, 0, 2, 5, 3]), array([0, 1, 5, 4, 2, 3])]
BEST :  33.0
#.#.........FINAL.........#.#
Best score: 33.0
Soln : [1 5 2 4 0 3]
#.#.........##.........#.#


# ---------------------------------------------------------

In [88]:
dm = create_random_citymap(5)
dm

array([[ 0.,  1.,  2.,  6.,  7.],
       [ 1.,  0.,  8.,  7., 10.],
       [ 2.,  8.,  0.,  5.,  8.],
       [ 6.,  7.,  5.,  0.,  6.],
       [ 7., 10.,  8.,  6.,  0.]])

In [142]:
pop = generate_population(3,5)
pop 

[array([1, 0, 4, 2, 3]), array([1, 3, 0, 4, 2]), array([2, 0, 4, 1, 3])]

In [143]:
sc = pop_score_list(pop,dm)
sc

array([28., 36., 31.])

In [150]:
[ pop[k] for k in np.argsort(sc)[:2]]

[array([1, 0, 4, 2, 3]), array([2, 0, 4, 1, 3])]

In [148]:
pop[[1,2]]

TypeError: list indices must be integers or slices, not list

In [133]:
pick_mate(50)

46

In [91]:
best = np.argmin(sc)
pop[best]

array([3, 1, 2, 0, 4])

In [64]:
s = rand_soln_tsp(5)
p = rand_soln_tsp(5)
s,p

(array([3, 4, 2, 0, 1]), array([4, 3, 1, 0, 2]))

In [59]:
crossover(s,p)

array([0, 2, 3, 4, 1])

In [65]:
mutate(s)

array([0, 4, 2, 3, 1])

In [16]:
s = rand_soln(dm)
s

array([0, 1, 0, 3, 2, 4])

In [220]:
fitness_fn(s,dm)

20.0

In [228]:
pop = generate_population(3,dm)
pop

[array([0, 2, 0, 4]), array([0, 2, 0, 2, 0, 4]), array([0, 4])]

In [243]:
pop_score_list(pop,dm)

array([10., 16.,  4.])

In [259]:
s = np.array([1,4,3,0])

In [260]:
t = s.argsort()
t

array([3, 0, 2, 1])

In [262]:
r = np.empty_like(t)
r

array([93999935849584,              0,              0,    -4294967295])

In [263]:
r[t] = np.arange(len(s))
r

array([1, 3, 2, 0])

In [264]:
[len(r)-x for x in r]

[3, 1, 2, 4]

In [1]:
b = [1,2,3,4]

In [2]:
c = b
c[1] = 5

In [3]:
b

[1, 5, 3, 4]

In [5]:
d = c[:]
c[0] = 4

In [6]:
d

[1, 5, 3, 4]

In [7]:
c

[4, 5, 3, 4]