In [17]:
import random
import numpy as np

In [7]:
def rand_soln(dist_mat): # shortest path to start to end
    #
    start = 0
    end = len(dist_mat) - 1
    
    route = np.array([start], dtype=int) # np.zeros(1, dtype=int)
    
    b_val = True
    pos = 0
    
    while b_val:
        values  = np.nonzero(dist_mat[route[pos]])
        rand_val = random.randint(0,len(values[0])-1)
        route = np.append(route, values[0][rand_val])
        
        if route[pos+1] == end :
            b_val = False
        else:
            pos += 1
    
    return route

In [5]:
def breed(parent1, parent2):
    child = []
    childP1 = []
    childP2 = []
    
    geneA = int(random.random() * len(parent1))
    geneB = int(random.random() * len(parent1))
    
    startGene = 5#min(geneA, geneB)
    endGene = 8#max(geneA, geneB)

    for i in range(startGene, endGene):
        childP1.append(parent1[i])
        
    childP2 = [item for item in parent2 if item not in childP1]

    child = childP1 + childP2
    return child

In [6]:
breed([1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1])

[6, 7, 8, 9, 5, 4, 3, 2, 1]

In [16]:
random.choice([0,1])

1

In [18]:
np.array([2,3])

array([2, 3])

In [20]:
s = np.arange(5)
s

array([0, 1, 2, 3, 4])

In [33]:
s[1],s[3] = s[3],s[1]

In [32]:
s

array([0, 1, 2, 3, 4])

In [37]:
ss = list(range(0,8))
ss

[0, 1, 2, 3, 4, 5, 6, 7]

In [38]:
p = ss[3:6]
p

[3, 4, 5]

In [39]:
p[1] = 12
p

[3, 12, 5]

In [40]:
ss

[0, 1, 2, 3, 4, 5, 6, 7]

In [41]:
ss[3] = 33

In [52]:
s1 = np.array(ss)
s2 = np.array(list(range(8,16)))
s1,s2

(array([ 0,  1,  2, 33,  4,  5,  6,  7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]))

In [55]:
s1

array([ 0,  1,  2, 33,  4,  5,  6,  7])

In [56]:
s2

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
np.concatenate([s1,s2],axis=0)

array([ 0,  1,  2, 33,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
ss

[0, 1, 2, 33, 4, 5, 6, 7]

In [69]:
b =ss[2]
b

2

In [70]:
b =323

In [71]:
ss

[0, 1, 2, 33, 4, 5, 6, 7]

In [72]:
ss

[0, 1, 2, 33, 4, 5, 6, 7]

In [76]:
cc = ss[:]

In [79]:
cc[2] = 779

In [80]:
cc,ss

([0, 1, 779, 33, 4, 5, 6, 7], [0, 1, 999, 33, 4, 5, 6, 7])